#import <UIKit/UIKit.h>

@interface UIColor (ZHColor)

	+ (UIColor *) fenhong;//粉红
	+ (UIColor *) feise;//妃色
	+ (UIColor *) pinhong;//品红
	+ (UIColor *) taohong;//桃红
	+ (UIColor *) haitanghong;//海棠红
	+ (UIColor *) shiliuhong;//石榴红
	+ (UIColor *) yingtaose;//樱桃色
	+ (UIColor *) yinhong;//银红
	+ (UIColor *) dahong;//大红
	+ (UIColor *) jiangzi;//绛紫
	+ (UIColor *) feihong;//绯红
	+ (UIColor *) yanzhi;//胭脂
	+ (UIColor *) zhuhong;//朱红
	+ (UIColor *) dan;//丹
	+ (UIColor *) tong;//彤
	+ (UIColor *) qianse;//茜色
	+ (UIColor *) huohong;//火红
	+ (UIColor *) hechi;//赫赤
	+ (UIColor *) yanhong;//嫣红
	+ (UIColor *) yanghong;//洋红
	+ (UIColor *) yan;//炎
	+ (UIColor *) chi;//赤
	+ (UIColor *) wan;//绾
	+ (UIColor *) zaohong;//枣红
	+ (UIColor *) tan;//檀
	+ (UIColor *) yanhong_;//殷红
	+ (UIColor *) tuohong;//酡红
	+ (UIColor *) tuoyan;//酡颜
	+ (UIColor *) ehuang;//鹅黄
	+ (UIColor *) yahuang;//鸭黄
	+ (UIColor *) yingcaose;//樱草色
	+ (UIColor *) xinghuang;//杏黄
	+ (UIColor *) xinghong;//杏红
	+ (UIColor *) juhuang;//橘黄
	+ (UIColor *) chenghuang;//橙黄
	+ (UIColor *) juhong;//橘红
	+ (UIColor *) jianghuang;//姜黄
	+ (UIColor *) xiangse;//缃色
	+ (UIColor *) chengse;//橙色
	+ (UIColor *) chase;//茶色
	+ (UIColor *) tuose;//驼色
	+ (UIColor *) hunhuang;//昏黄
	+ (UIColor *) lise;//栗色
	+ (UIColor *) zongse;//棕色
	+ (UIColor *) zonglv;//棕绿
	+ (UIColor *) zonghei;//棕黑
	+ (UIColor *) zonghong;//棕红
	+ (UIColor *) zonghuang;//棕黄
	+ (UIColor *) zhese;//赭色
	+ (UIColor *) hupo;//琥珀
	+ (UIColor *) hese;//褐色
	+ (UIColor *) kuhuang;//枯黄
	+ (UIColor *) huanglu;//黄栌
	+ (UIColor *) qiuse;//秋色
	+ (UIColor *) qiuxiangse;//秋香色
	+ (UIColor *) nenlv;//嫩绿
	+ (UIColor *) liuhuang;//柳黄
	+ (UIColor *) liulv;//柳绿
	+ (UIColor *) zhuqing;//竹青
	+ (UIColor *) conghuang;//葱黄
	+ (UIColor *) conglv;//葱绿
	+ (UIColor *) congqing;//葱青
	+ (UIColor *) qingcong;//青葱
	+ (UIColor *) youlv;//油绿
	+ (UIColor *) lvchen;//绿沉
	+ (UIColor *) bise;//碧色
	+ (UIColor *) bilv;//碧绿
	+ (UIColor *) qingbi;//青碧
	+ (UIColor *) feicuise;//翡翠色
	+ (UIColor *) caolv;//草绿
	+ (UIColor *) qingse;//青色
	+ (UIColor *) qingcui;//青翠
	+ (UIColor *) qingbai;//青白
	+ (UIColor *) yaluanqing;//鸭卵青
	+ (UIColor *) xiekeqing;//蟹壳青
	+ (UIColor *) yaqing;//鸦青
	+ (UIColor *) lvse;//绿色
	+ (UIColor *) doulv;//豆绿
	+ (UIColor *) douqing;//豆青
	+ (UIColor *) shiqing;//石青
	+ (UIColor *) yuse;//玉色
	+ (UIColor *) piao;//缥
	+ (UIColor *) ailv;//艾绿
	+ (UIColor *) songbailv;//松柏绿
	+ (UIColor *) songhualv;//松花绿
	+ (UIColor *) songhuase;//松花色
	+ (UIColor *) lan;//蓝
	+ (UIColor *) dianqing;//靛青
	+ (UIColor *) dianlan;//靛蓝
	+ (UIColor *) bilan;//碧蓝
	+ (UIColor *) weilan;//蔚蓝
	+ (UIColor *) baolan;//宝蓝
	+ (UIColor *) lanhuise;//蓝灰色
	+ (UIColor *) zangqing;//藏青
	+ (UIColor *) zanglan;//藏蓝
	+ (UIColor *) dai;//黛
	+ (UIColor *) dailv;//黛绿
	+ (UIColor *) dailan;//黛蓝
	+ (UIColor *) daizi;//黛紫
	+ (UIColor *) zise;//紫色
	+ (UIColor *) zijiang;//紫酱
	+ (UIColor *) jiangzi_;//酱紫
	+ (UIColor *) zitan;//紫檀
	+ (UIColor *) ganqing;//绀青
	+ (UIColor *) zitang;//紫棠
	+ (UIColor *) qinglian;//青莲
	+ (UIColor *) qunqing;//群青
	+ (UIColor *) xueqing;//雪青
	+ (UIColor *) dingxiangse;//丁香色
	+ (UIColor *) ouse;//藕色
	+ (UIColor *) ouhese;//藕荷色
	+ (UIColor *) cangse;//苍色
	+ (UIColor *) canghuang;//苍黄
	+ (UIColor *) cangqing;//苍青
	+ (UIColor *) canghei;//苍黑
	+ (UIColor *) cangbai;//苍白
	+ (UIColor *) shuise;//水色
	+ (UIColor *) shuihong;//水红
	+ (UIColor *) shuilv;//水绿
	+ (UIColor *) shuilan;//水蓝
	+ (UIColor *) danqing;//淡青
	+ (UIColor *) hulan;//湖蓝
	+ (UIColor *) hulv;//湖绿
	+ (UIColor *) jingbai;//精白
	+ (UIColor *) xiangyabai;//像牙白
	+ (UIColor *) xuebai;//雪白
	+ (UIColor *) yuebai;//月白
	+ (UIColor *) gao;//缟
	+ (UIColor *) su;//素
	+ (UIColor *) tubai;//荼白
	+ (UIColor *) shuangse;//霜色
	+ (UIColor *) huabai;//花白
	+ (UIColor *) yudubai;//鱼肚白
	+ (UIColor *) yingbai;//莹白
	+ (UIColor *) huise;//灰色
	+ (UIColor *) yase;//牙色
	+ (UIColor *) qianbai;//铅白
	+ (UIColor *) xuanse;//玄色
	+ (UIColor *) xuanqing;//玄青
	+ (UIColor *) wuse;//乌色
	+ (UIColor *) wuhei;//乌黑
	+ (UIColor *) qihei;//漆黑
	+ (UIColor *) mose;//墨色
	+ (UIColor *) mohui;//墨灰
	+ (UIColor *) heise;//黑色
	+ (UIColor *) zise_;//缁色
	+ (UIColor *) meihei;//煤黑
	+ (UIColor *) li;//黧
	+ (UIColor *) li_;//黎
	+ (UIColor *) you;//黝
	+ (UIColor *) youhei;//黝黑
	+ (UIColor *) an;//黯
	+ (UIColor *) chijin;//赤金
	+ (UIColor *) jinse;//金色
	+ (UIColor *) yinbai;//银白
	+ (UIColor *) tonglv;//铜绿
	+ (UIColor *) wujin;//乌金
	+ (UIColor *) laoyin;//老银
	+ (UIColor *) yinzhu;//银朱
	+ (UIColor *) zhusha;//朱砂
	+ (UIColor *) zhubiao;//朱膘
	+ (UIColor *) zheshi;//赭石
	+ (UIColor *) shilv;//石绿
	+ (UIColor *) baifen;//白粉
	+ (UIColor *) huaqing;//花青
	+ (UIColor *) tenghuang;//藤黄
	+ (UIColor *) cihuang;//雌黄
	+ (UIColor *) xionghuang;//雄黄

@end