#import <UIKit/UIKit.h>

@interface UIColor (ZHColor)

	+ (UIColor *) baicaoshuang;//百草霜
	+ (UIColor *) baifanghuilan;//柏坊灰蓝
	+ (UIColor *) baolan;//宝蓝
	+ (UIColor *) beijingmaolan;//北京毛蓝
	+ (UIColor *) biyushi;//碧玉石
	+ (UIColor *) canghuang;//苍黄
	+ (UIColor *) zanglan;//藏蓝
	+ (UIColor *) canglyu;//苍绿
	+ (UIColor *) caohuang;//草黄
	+ (UIColor *) chengdehui;//承德灰
	+ (UIColor *) chengdezao;//承德皂
	+ (UIColor *) chensha;//辰砂
	+ (UIColor *) chunlan;//春蓝
	+ (UIColor *) chunlyu;//春绿
	+ (UIColor *) cuilyu;//翠绿
	+ (UIColor *) cujingzao;//粗晶皂
	+ (UIColor *) dachijin;//大赤金
	+ (UIColor *) dailan;//黛蓝
	+ (UIColor *) dandongshi;//丹东石
	+ (UIColor *) danhuilyu;//淡灰绿
	+ (UIColor *) dengcaohui;//灯草灰
	+ (UIColor *) dianlan;//靛蓝
	+ (UIColor *) fanqiehong;//蕃茄红
	+ (UIColor *) feihong;//妃红
	+ (UIColor *) gancaohuang;//甘草黄
	+ (UIColor *) ganlanlyu;//橄榄绿
	+ (UIColor *) ganshifen;//甘石粉
	+ (UIColor *) gulan;//钴蓝
	+ (UIColor *) guohui;//果灰
	+ (UIColor *) hailan;//海蓝
	+ (UIColor *) hongzao;//红皂
	+ (UIColor *) huanghui;//黄灰
	+ (UIColor *) huaqing;//花青
	+ (UIColor *) hufen;//胡粉
	+ (UIColor *) huilan;//灰蓝
	+ (UIColor *) huilyu;//灰绿
	+ (UIColor *) huimi;//灰米
	+ (UIColor *) jianghuang;//姜黄
	+ (UIColor *) jiangxiaoni;//将校呢
	+ (UIColor *) jiangzi;//绛紫
	+ (UIColor *) jiehong;//桔红
	+ (UIColor *) jiehuang;//桔黄
	+ (UIColor *) jinhuang;//金黄
	+ (UIColor *) junlyu;//军绿
	+ (UIColor *) kongquelan;//孔雀蓝
	+ (UIColor *) kujin;//库金
	+ (UIColor *) kulyu;//枯绿
	+ (UIColor *) labai;//蜡白
	+ (UIColor *) laolyu;//老绿
	+ (UIColor *) liuhuahong;//榴花红
	+ (UIColor *) luhui;//芦灰
	+ (UIColor *) meiguihong;//玫瑰红
	+ (UIColor *) meiguihui;//玫瑰灰
	+ (UIColor *) mihong;//米红
	+ (UIColor *) mihui;//米灰
	+ (UIColor *) mise;//米色
	+ (UIColor *) nailyu;//奶绿
	+ (UIColor *) naizong;//奶棕
	+ (UIColor *) ningmenghuang;//柠檬黄
	+ (UIColor *) pinhong;//品红
	+ (UIColor *) qianhaichanglan;//浅海昌蓝
	+ (UIColor *) qianhuangzong;//浅黄棕
	+ (UIColor *) qianjiehuang;//浅桔黄
	+ (UIColor *) qianniuzi;//牵牛紫
	+ (UIColor *) qianshiyingzi;//浅石英紫
	+ (UIColor *) qiantengzi;//浅藤紫
	+ (UIColor *) qiantuose;//浅驼色
	+ (UIColor *) qianxieya;//浅血牙
	+ (UIColor *) qianzonghui;//浅棕灰
	+ (UIColor *) kaqihuang;//卡其黄
	+ (UIColor *) kaqilyu;//卡其绿
	+ (UIColor *) qiepizi;//茄皮紫
	+ (UIColor *) quehui;//鹊灰
	+ (UIColor *) ronglan;//绒蓝
	+ (UIColor *) sanlyu;//三绿
	+ (UIColor *) shalyu;//沙绿
	+ (UIColor *) shaqing;//沙青
	+ (UIColor *) shenyan;//深烟
	+ (UIColor *) shenyanhong;//深烟红
	+ (UIColor *) shenzhuyue;//深竹月
	+ (UIColor *) shiyangjin;//十样锦
	+ (UIColor *) shuidiaohui;//水貂灰
	+ (UIColor *) shuihuang;//水黄
	+ (UIColor *) tenghuang;//藤黄
	+ (UIColor *) tianqing;//天青*
	+ (UIColor *) tiehui;//铁灰
	+ (UIColor *) tuhuang;//土黄
	+ (UIColor *) xiangsihui;//相思灰
	+ (UIColor *) xiehong;//血红
	+ (UIColor *) xinghong;//猩红
	+ (UIColor *) xionghuang;//雄黄
	+ (UIColor *) xiongjing;//雄精
	+ (UIColor *) xiuhong;//锈红
	+ (UIColor *) xiulyu;//锈绿
	+ (UIColor *) xuanjin;//选金
	+ (UIColor *) xuese;//雪色
	+ (UIColor *) xuezi;//雪紫
	+ (UIColor *) yadanqing;//鸭蛋青
	+ (UIColor *) yangcongzi;//洋葱紫
	+ (UIColor *) yanghong;//洋红
	+ (UIColor *) yanhong;//艳红
	+ (UIColor *) yingwulyu;//鹦鹉绿
	+ (UIColor *) yinzhu;//银朱
	+ (UIColor *) youlyu;//油绿
	+ (UIColor *) youyanmo;//油烟墨
	+ (UIColor *) yuanqing;//元青
	+ (UIColor *) yanzhi;//胭脂
	+ (UIColor *) yinbo;//银箔
	+ (UIColor *) yuejihong;//月季红
	+ (UIColor *) yushilan;//玉石蓝
	+ (UIColor *) zaohong;//枣红
	+ (UIColor *) zhangdan;//章丹
	+ (UIColor *) zhenghui;//正灰
	+ (UIColor *) zhihuang;//枝黄
	+ (UIColor *) zhijinhui;//织锦灰
	+ (UIColor *) zhizong;//纸棕
	+ (UIColor *) zhongzonghui;//中棕灰
	+ (UIColor *) zifen;//紫粉
	+ (UIColor *) zishuijing;//紫水晶
	+ (UIColor *) zitenghui;//紫藤灰
	+ (UIColor *) ziweihua;//紫薇花
	+ (UIColor *) zongcha;//棕茶

@end