#import <UIKit/UIKit.h>

@interface UIColor (JPColor)

	+ (UIColor *) gudaizi;//古代紫
	+ (UIColor *) qiezigan;//茄子紺
	+ (UIColor *) erlan;//二藍
	+ (UIColor *) jingzi;//京紫
	+ (UIColor *) pupu;//蒲葡
	+ (UIColor *) ruozi;//若紫
	+ (UIColor *) hongzi;//紅紫
	+ (UIColor *) meizi;//梅紫
	+ (UIColor *) changpu;//菖蒲
	+ (UIColor *) hongteng;//紅藤
	+ (UIColor *) qianzi;//浅紫
	+ (UIColor *) zishuijing;//紫水晶
	+ (UIColor *) baomeishu;//薄梅鼠
	+ (UIColor *) xiaoshu;//暁鼠
	+ (UIColor *) mudanshu;//牡丹鼠
	+ (UIColor *) xia;//霞
	+ (UIColor *) tengshu;//藤鼠
	+ (UIColor *) ban;//半
	+ (UIColor *) bao;//薄
	+ (UIColor *) baoshu;//薄鼠
	+ (UIColor *) jiuyushu;//鳩羽鼠
	+ (UIColor *) jiuyu;//鳩羽
	+ (UIColor *) jiegengshu;//桔梗鼠
	+ (UIColor *) zishu;//紫鼠
	+ (UIColor *) putaoshu;//葡萄鼠
	+ (UIColor *) nong;//濃
	+ (UIColor *) ziyuan;//紫鳶
	+ (UIColor *) nongshu;//濃鼠
	+ (UIColor *) tengmeizhu;//藤煤竹
	+ (UIColor *) miezi;//滅紫
	+ (UIColor *) hongxiaoshu;//紅消鼠
	+ (UIColor *) siせzi;//似せ紫
	+ (UIColor *) huihuanglv ;//灰黄緑 
	+ (UIColor *) qiaomaiqiese ;//蕎麦切色 
	+ (UIColor *) baoyunshu;//薄雲鼠
	+ (UIColor *) kuye;//枯野
	+ (UIColor *) run;//潤
	+ (UIColor *) lixiubaicha;//利休白茶
	+ (UIColor *) chashu;//茶鼠
	+ (UIColor *) hutaoran;//胡桃染
	+ (UIColor *) jianghushu;//江戸鼠
	+ (UIColor *) mei;//煤
	+ (UIColor *) dingzicha;//丁子茶
	+ (UIColor *) chairan;//柴染
	+ (UIColor *) zongyuntangcha;//宗伝唐茶
	+ (UIColor *) licha;//砺茶
	+ (UIColor *) jiancha;//煎茶
	+ (UIColor *) yinmeizhu;//銀煤竹
	+ (UIColor *) huangkucha;//黄枯茶
	+ (UIColor *) meizhu;//煤竹
	+ (UIColor *) jiaocha;//焦茶
	+ (UIColor *) heixiang;//黒橡
	+ (UIColor *) xianfa;//憲法
	+ (UIColor *) nie;//涅
	+ (UIColor *) binlangziran;//檳榔子染
	+ (UIColor *) heiyuan;//黒鳶
	+ (UIColor *) chimo;//赤墨
	+ (UIColor *) heihong;//黒紅
	+ (UIColor *) bai;//白
	+ (UIColor *) hufen;//胡粉
	+ (UIColor *) maoのhua;//卯の花
	+ (UIColor *) baici;//白磁
	+ (UIColor *) shengchengり;//生成り
	+ (UIColor *) rubai;//乳白
	+ (UIColor *) bailian;//白練
	+ (UIColor *) su;//素
	+ (UIColor *) baimeishu;//白梅鼠
	+ (UIColor *) baishu;//白鼠
	+ (UIColor *) juanshu;//絹鼠
	+ (UIColor *) huiqing;//灰青
	+ (UIColor *) yinshu;//銀鼠
	+ (UIColor *) baodun;//薄鈍
	+ (UIColor *) baomo;//薄墨
	+ (UIColor *) xi;//錫
	+ (UIColor *) sushu;//素鼠
	+ (UIColor *) shu;//鼠
	+ (UIColor *) yuanshishu;//源氏鼠
	+ (UIColor *) hui;//灰
	+ (UIColor *) qian;//鉛
	+ (UIColor *) dun;//鈍
	+ (UIColor *) mo;//墨
	+ (UIColor *) jingshu;//丼鼠
	+ (UIColor *) xiaotan;//消炭
	+ (UIColor *) lanmocha;//藍墨茶
	+ (UIColor *) yanggeng;//羊羹
	+ (UIColor *) la;//蝋
	+ (UIColor *) hei;//黒
	+ (UIColor *) wuyu;//烏羽
	+ (UIColor *) tiehei;//鉄黒
	+ (UIColor *) ruyu;//濡羽
	+ (UIColor *) heitan;//黒壇
	+ (UIColor *) xianfaheicha;//憲法黒茶
	+ (UIColor *) anhei;//暗黒
	+ (UIColor *) mengcong;//萌葱
	+ (UIColor *) hualvqing;//花緑青
	+ (UIColor *) feicui;//翡翠
	+ (UIColor *) qinglv;//青緑
	+ (UIColor *) shuiqiancong;//水浅葱
	+ (UIColor *) qingqiancong;//錆浅葱
	+ (UIColor *) qingbi;//青碧
	+ (UIColor *) yuzhaocha;//御召茶
	+ (UIColor *) coushu;//湊鼠
	+ (UIColor *) gaolinahu;//高麗納戸
	+ (UIColor *) bairucha;//百入茶
	+ (UIColor *) qingshu;//錆鼠
	+ (UIColor *) qingtieyunahu;//錆鉄御納戸
	+ (UIColor *) lanshu;//藍鼠
	+ (UIColor *) qingyunahu;//錆御納戸
	+ (UIColor *) chuanhua;//舛花
	+ (UIColor *) yundoumuhua;//熨斗目花
	+ (UIColor *) yuzhaoyunahu;//御召御納戸
	+ (UIColor *) tieyunahu;//鉄御納戸
	+ (UIColor *) ganshu ;//紺鼠 
	+ (UIColor *) lantie;//藍鉄
	+ (UIColor *) qinghe;//青褐
	+ (UIColor *) hefan;//褐返
	+ (UIColor *) he;//褐
	+ (UIColor *) yuebai;//月白
	+ (UIColor *) baijin;//白菫
	+ (UIColor *) baihua;//白花
	+ (UIColor *) lanbai;//藍白
	+ (UIColor *) bailan;//白藍
	+ (UIColor *) shui;//水
	+ (UIColor *) pingsi;//瓶覗
	+ (UIColor *) mi;//秘
	+ (UIColor *) kong;//空
	+ (UIColor *) wuwangcao;//勿忘草
	+ (UIColor *) qingteng;//青藤
	+ (UIColor *) baiqun;//白群
	+ (UIColor *) qianpiao;//浅縹
	+ (UIColor *) baohua;//薄花
	+ (UIColor *) nahu;//納戸
	+ (UIColor *) qiancong;//浅葱
	+ (UIColor *) huaqiancong;//花浅葱
	+ (UIColor *) xinqiao;//新橋
	+ (UIColor *) tian;//天
	+ (UIColor *) loucao;//露草
	+ (UIColor *) qing;//青
	+ (UIColor *) baolan;//薄藍
	+ (UIColor *) piao;//縹
	+ (UIColor *) ganbi;//紺碧
	+ (UIColor *) baoqunqing;//薄群青
	+ (UIColor *) baohuaying;//薄花桜
	+ (UIColor *) qunqing;//群青
	+ (UIColor *) duruo;//杜若
	+ (UIColor *) liuli;//瑠璃
	+ (UIColor *) baopiao;//薄縹
	+ (UIColor *) liuligan;//瑠璃紺
	+ (UIColor *) ganliuli ;//紺瑠璃 
	+ (UIColor *) lan;//藍
	+ (UIColor *) qinglan;//青藍
	+ (UIColor *) shenpiao;//深縹
	+ (UIColor *) gan;//紺
	+ (UIColor *) ganqing;//紺青
	+ (UIColor *) liugan;//留紺
	+ (UIColor *) nonglan;//濃藍
	+ (UIColor *) tiegan;//鉄紺
	+ (UIColor *) qihei;//漆黒
	+ (UIColor *) danteng;//淡藤
	+ (UIColor *) teng;//藤
	+ (UIColor *) hongguakong;//紅掛空
	+ (UIColor *) hongbi;//紅碧
	+ (UIColor *) ganjiegeng;//紺桔梗
	+ (UIColor *) hua;//花
	+ (UIColor *) ganlan;//紺藍
	+ (UIColor *) hongjiegeng;//紅桔梗
	+ (UIColor *) jiegeng;//桔梗
	+ (UIColor *) tengnahu;//藤納戸
	+ (UIColor *) hongguahua;//紅掛花
	+ (UIColor *) ziyuan;//紫苑
	+ (UIColor *) baiteng;//白藤
	+ (UIColor *) tengzi;//藤紫
	+ (UIColor *) jin;//菫
	+ (UIColor *) qingzi;//青紫
	+ (UIColor *) changpu;//菖蒲
	+ (UIColor *) longdan;//竜胆
	+ (UIColor *) jianghuzi;//江戸紫
	+ (UIColor *) benzi;//本紫
	+ (UIColor *) putao;//葡萄
	+ (UIColor *) shenzi;//深紫
	+ (UIColor *) zihei;//紫黒
	+ (UIColor *) zi;//紫
	+ (UIColor *) baoputao;//薄葡萄
	+ (UIColor *) zigan;//紫紺
	+ (UIColor *) anhong;//暗紅
	+ (UIColor *) sangのshi;//桑の実
	+ (UIColor *) huangjin;//黄金
	+ (UIColor *) luran;//櫨染
	+ (UIColor *) huangxiuyese ;//黄朽葉色 
	+ (UIColor *) shanchuicha;//山吹茶
	+ (UIColor *) jiezi;//芥子
	+ (UIColor *) douがらcha;//豆がら茶
	+ (UIColor *) quchen;//麹塵
	+ (UIColor *) shanjiu;//山鳩
	+ (UIColor *) lixiushu;//利休鼠
	+ (UIColor *) haisongcha;//海松茶
	+ (UIColor *) lanhaisongcha;//藍海松茶
	+ (UIColor *) lanmeicha;//藍媚茶
	+ (UIColor *) qiansuicha;//千歳茶
	+ (UIColor *) yanjingcha;//岩井茶
	+ (UIColor *) xianzhaicha;//仙斎茶
	+ (UIColor *) heilv;//黒緑
	+ (UIColor *) liumeizhu;//柳煤竹
	+ (UIColor *) huacha;//樺茶
	+ (UIColor *) kongwubeizi;//空五倍子
	+ (UIColor *) shengbi;//生壁
	+ (UIColor *) feihoumeizhu;//肥後煤竹
	+ (UIColor *) meicha;//媚茶
	+ (UIColor *) baixiang;//白橡
	+ (UIColor *) yama;//亜麻
	+ (UIColor *) zhen;//榛
	+ (UIColor *) huizhi;//灰汁
	+ (UIColor *) lixiucha;//利休茶
	+ (UIColor *) yingcha;//鶯茶
	+ (UIColor *) mulan;//木蘭
	+ (UIColor *) sha;//砂
	+ (UIColor *) you;//油
	+ (UIColor *) lixiu;//利休
	+ (UIColor *) meixingcha;//梅幸茶
	+ (UIColor *) likuancha;//璃寛茶
	+ (UIColor *) huanghaisongcha;//黄海松茶
	+ (UIColor *) caizhongyou;//菜種油
	+ (UIColor *) qingxiuye;//青朽葉
	+ (UIColor *) genan;//根岸
	+ (UIColor *) ruocha;//鶸茶
	+ (UIColor *) liucha;//柳茶
	+ (UIColor *) haisong;//海松
	+ (UIColor *) ying;//鶯
	+ (UIColor *) lvhuang;//緑黄
	+ (UIColor *) ruo;//鶸
	+ (UIColor *) mocha;//抹茶
	+ (UIColor *) ruocao;//若草
	+ (UIColor *) huanglv;//黄緑
	+ (UIColor *) ruoya;//若芽
	+ (UIColor *) ruocai;//若菜
	+ (UIColor *) ruomiaose ;//若苗色 
	+ (UIColor *) qingdan;//青丹
	+ (UIColor *) cao;//草
	+ (UIColor *) tai;//苔
	+ (UIColor *) menghuang;//萌黄
	+ (UIColor *) miao;//苗
	+ (UIColor *) ruoye;//若葉
	+ (UIColor *) songye;//松葉
	+ (UIColor *) xiachong;//夏虫
	+ (UIColor *) ruomenghuang;//鶸萌黄
	+ (UIColor *) liu;//柳
	+ (UIColor *) qingbaixiang;//青白橡
	+ (UIColor *) liushu;//柳鼠
	+ (UIColor *) liyeliu;//裏葉柳
	+ (UIColor *) shankui;//山葵
	+ (UIColor *) laozhu;//老竹
	+ (UIColor *) bailv ;//白緑 
	+ (UIColor *) danmenghuang ;//淡萌黄 
	+ (UIColor *) liuran;//柳染
	+ (UIColor *) baomengcong;//薄萌葱
	+ (UIColor *) shenchuanshu;//深川鼠
	+ (UIColor *) ruolv;//若緑
	+ (UIColor *) qianlv;//浅緑
	+ (UIColor *) baolv;//薄緑
	+ (UIColor *) qingdun;//青鈍
	+ (UIColor *) qingcishu;//青磁鼠
	+ (UIColor *) baoqing;//薄青
	+ (UIColor *) qingqingci;//錆青磁
	+ (UIColor *) lvqing;//緑青
	+ (UIColor *) qiansuilv;//千歳緑
	+ (UIColor *) ruozhu;//若竹
	+ (UIColor *) lv;//緑
	+ (UIColor *) changpan;//常磐
	+ (UIColor *) qiancaoshu;//千草鼠
	+ (UIColor *) qiancao;//千草
	+ (UIColor *) qingci;//青磁
	+ (UIColor *) qingzhu;//青竹
	+ (UIColor *) changpanlv;//常磐緑
	+ (UIColor *) muzei;//木賊
	+ (UIColor *) tianerong ;//天鵞絨 
	+ (UIColor *) chongao;//虫襖
	+ (UIColor *) ge;//革
	+ (UIColor *) shenlv;//深緑
	+ (UIColor *) tie;//鉄
	+ (UIColor *) xiaodou;//小豆
	+ (UIColor *) kucha;//枯茶
	+ (UIColor *) yi;//饴
	+ (UIColor *) luotuo;//骆驼
	+ (UIColor *) tu;//土
	+ (UIColor *) huangtang;//黄唐
	+ (UIColor *) sangran;//桑染
	+ (UIColor *) lu;//栌
	+ (UIColor *) huangxiang;//黄橡
	+ (UIColor *) dingziran;//丁字染
	+ (UIColor *) xiangran;//香染
	+ (UIColor *) pipacha;//枇杷茶
	+ (UIColor *) zhiwancha;//芝翫茶
	+ (UIColor *) jiaoxiang;//焦香
	+ (UIColor *) hutao;//胡桃
	+ (UIColor *) sezhi;//渋纸
	+ (UIColor *) xiuye;//朽葉
	+ (UIColor *) sangcha;//桑茶
	+ (UIColor *) lukaocha;//路考茶
	+ (UIColor *) guofang;//国防
	+ (UIColor *) qieluo;//伽羅
	+ (UIColor *) jianghucha;//江戸茶
	+ (UIColor *) hua;//樺
	+ (UIColor *) hongyujin;//紅鬱金
	+ (UIColor *) tuqi;//土器
	+ (UIColor *) hu;//狐
	+ (UIColor *) huangtu;//黄土
	+ (UIColor *) hupo;//琥珀
	+ (UIColor *) chicha;//赤茶
	+ (UIColor *) daizhe;//代赭
	+ (UIColor *) lianwa;//煉瓦
	+ (UIColor *) quecha;//雀茶
	+ (UIColor *) tuanshilangcha;//団十郎茶
	+ (UIColor *) shise;//柿渋
	+ (UIColor *) hongyuan;//紅鳶
	+ (UIColor *) huicha;//灰茶
	+ (UIColor *) cha;//茶
	+ (UIColor *) guipi;//檜皮
	+ (UIColor *) yuan;//鳶
	+ (UIColor *) shicha;//柿茶
	+ (UIColor *) bianbing;//弁柄
	+ (UIColor *) chiqing;//赤錆
	+ (UIColor *) he;//褐
	+ (UIColor *) limei;//栗梅
	+ (UIColor *) hongguipi;//紅檜皮
	+ (UIColor *) hailaocha;//海老茶
	+ (UIColor *) tangcha;//唐茶
	+ (UIColor *) li;//栗
	+ (UIColor *) chitong;//赤銅
	+ (UIColor *) qing;//錆
	+ (UIColor *) chihe;//赤褐
	+ (UIColor *) chahe;//茶褐
	+ (UIColor *) lipicha;//栗皮茶
	+ (UIColor *) heicha;//黒茶
	+ (UIColor *) putaocha;//葡萄茶
	+ (UIColor *) putao;//葡萄
	+ (UIColor *) xuancao;//萱草
	+ (UIColor *) ganzi;//柑子
	+ (UIColor *) jincha;//金茶
	+ (UIColor *) migan;//蜜柑
	+ (UIColor *) qiandan;//鉛丹
	+ (UIColor *) huangdan;//黄丹
	+ (UIColor *) shi;//柿
	+ (UIColor *) huangchi;//黄赤
	+ (UIColor *) renshen;//人参
	+ (UIColor *) cheng;//橙
	+ (UIColor *) zhaoshi;//照柿
	+ (UIColor *) chicheng;//赤橙
	+ (UIColor *) jinchi;//金赤
	+ (UIColor *) zhu;//朱
	+ (UIColor *) xiaomai;//小麦
	+ (UIColor *) dan;//丹
	+ (UIColor *) huangcha;//黄茶
	+ (UIColor *) rougui;//肉桂
	+ (UIColor *) chixiuye;//赤朽葉
	+ (UIColor *) huangluran;//黄櫨染
	+ (UIColor *) pugongying;//蒲公英
	+ (UIColor *) huang;//黄
	+ (UIColor *) zhonghuang;//中黄
	+ (UIColor *) caiのhua;//菜の花
	+ (UIColor *) huangbo;//黄檗
	+ (UIColor *) luan;//卵
	+ (UIColor *) huaye;//花葉
	+ (UIColor *) yian;//刈安
	+ (UIColor *) yushushu;//玉蜀黍
	+ (UIColor *) jinmique;//金糸雀
	+ (UIColor *) huangzhizi;//黄支子
	+ (UIColor *) zhizi;//支子
	+ (UIColor *) xiangrikui;//向日葵
	+ (UIColor *) shanchui;//山吹
	+ (UIColor *) yujin;//鬱金
	+ (UIColor *) tenghuang;//藤黄
	+ (UIColor *) jin;//金
	+ (UIColor *) ying;//桜
	+ (UIColor *) baoying;//薄桜
	+ (UIColor *) yingshu;//桜鼠
	+ (UIColor *) baoshu;//鸨鼠
	+ (UIColor *) hong;//虹
	+ (UIColor *) shanhu;//珊瑚
	+ (UIColor *) yijinran;//一斤染
	+ (UIColor *) rou;//宍
	+ (UIColor *) hongmei;//红梅
	+ (UIColor *) baohong;//薄红
	+ (UIColor *) shensanhong;//甚三红
	+ (UIColor *) tao;//桃
	+ (UIColor *) bao;//鸨
	+ (UIColor *) fuzi;//撫子
	+ (UIColor *) huimei;//灰梅
	+ (UIColor *) huiying;//灰桜
	+ (UIColor *) danhongteng;//淡红藤
	+ (UIColor *) shizhu;//石竹
	+ (UIColor *) baohongmei;//薄红梅
	+ (UIColor *) taohua;//桃花
	+ (UIColor *) shuishi;//水柿
	+ (UIColor *) ときがらcha;//ときがら茶
	+ (UIColor *) tuihong;//退红
	+ (UIColor *) baoshi;//薄柿
	+ (UIColor *) changchun;//长春
	+ (UIColor *) meishu;//梅鼠
	+ (UIColor *) baoqiancong;//鸨浅葱
	+ (UIColor *) meiran;//梅染
	+ (UIColor *) sufangxiang;//苏芳香
	+ (UIColor *) qiansufang;//浅苏芳
	+ (UIColor *) zhenzhu;//真朱
	+ (UIColor *) chizi;//赤紫
	+ (UIColor *) zhizhu;//躑躅
	+ (UIColor *) mudan;//牡丹
	+ (UIColor *) jinyang;//今样
	+ (UIColor *) zhonghong;//中红
	+ (UIColor *) qiangwei;//蔷薇
	+ (UIColor *) hanhong;//韩红
	+ (UIColor *) yinzhu;//银朱
	+ (UIColor *) chihong;//赤红
	+ (UIColor *) hongfei;//红緋
	+ (UIColor *) chi;//赤
	+ (UIColor *) xingfei;//猩緋
	+ (UIColor *) hong;//红
	+ (UIColor *) shenfei;//深緋
	+ (UIColor *) fei;//绯
	+ (UIColor *) chidan;//赤丹
	+ (UIColor *) hongchi;//红赤
	+ (UIColor *) yanzhi;//胭脂
	+ (UIColor *) zhufei;//朱緋
	+ (UIColor *) qian;//茜
	+ (UIColor *) shenhailaocha;//深海老茶
	+ (UIColor *) sufang;//苏芳
	+ (UIColor *) zhenhong;//真红
	+ (UIColor *) nonghong;//浓红
	+ (UIColor *) xiangya;//象牙
	+ (UIColor *) lian;//练
	+ (UIColor *) huibai;//灰白
	+ (UIColor *) zhengli;//蒸栗
	+ (UIColor *) nvlanghua;//女郎花
	+ (UIColor *) kucao;//枯草
	+ (UIColor *) danhuang;//淡黄
	+ (UIColor *) baicha;//白茶
	+ (UIColor *) chibaixiang;//赤白橡
	+ (UIColor *) xishi;//洗柿
	+ (UIColor *) niaoのzi;//鸟の子
	+ (UIColor *) fengmi;//蜂蜜
	+ (UIColor *) ji;//肌
	+ (UIColor *) baoluan;//薄卵
	+ (UIColor *) xionghuang;//雄黄
	+ (UIColor *) saluoshi;//洒落柿
	+ (UIColor *) chixiang;//赤香
	+ (UIColor *) difen;//砥粉
	+ (UIColor *) rou;//肉
	+ (UIColor *) ren;//人
	+ (UIColor *) dingzi;//丁子
	+ (UIColor *) xiang;//香
	+ (UIColor *) baoxiang;//薄香
	+ (UIColor *) qianhuang;//浅黄
	+ (UIColor *) ku;//枯
	+ (UIColor *) danxiang;//淡香
	+ (UIColor *) xing;//杏
	+ (UIColor *) dongyun;//东云
	+ (UIColor *) shu;//曙
	+ (UIColor *) shanhuzhu;//珊瑚朱
	+ (UIColor *) shenzhizi;//深支子
	+ (UIColor *) xun;//纁
	+ (UIColor *) qianfei;//浅绯
	+ (UIColor *) zhenzhe;//真赭
	+ (UIColor *) xizhu;//洗朱
	+ (UIColor *) yuanzhoucha;//遠州茶
	+ (UIColor *) honghua;//红桦
	+ (UIColor *) zhe;//赭

@end