#import <UIKit/UIKit.h>

@interface UIColor (ZHColor)

	+ (UIColor *) weilan;//蔚蓝
	+ (UIColor *) lan;//蓝
	+ (UIColor *) bilan;//碧蓝
	+ (UIColor *) shiqing;//石青
	+ (UIColor *) dianqing;//靛青
	+ (UIColor *) dianlan;//靛蓝
	+ (UIColor *) huaqing;//花青
	+ (UIColor *) baolan;//宝蓝
	+ (UIColor *) lanhui;//蓝灰
	+ (UIColor *) zangqing;//藏青
	+ (UIColor *) zanglan;//藏蓝
	+ (UIColor *) dai;//黛
	+ (UIColor *) dailv;//黛绿
	+ (UIColor *) dailan;//黛蓝
	+ (UIColor *) daizi;//黛紫
	+ (UIColor *) zi;//紫
	+ (UIColor *) zijiang;//紫酱
	+ (UIColor *) jiangzi;//酱紫
	+ (UIColor *) zitan;//紫檀
	+ (UIColor *) ganqing;//绀青
	+ (UIColor *) zitang;//紫棠
	+ (UIColor *) qinglian;//青莲
	+ (UIColor *) qunqing;//群青
	+ (UIColor *) xueqing;//雪青
	+ (UIColor *) dingxiang;//丁香
	+ (UIColor *) ou;//藕
	+ (UIColor *) ouhe;//藕荷
	+ (UIColor *) zhusha;//朱砂
	+ (UIColor *) huohong;//火红
	+ (UIColor *) zhubiao;//朱膘
	+ (UIColor *) fei;//妃
	+ (UIColor *) yanghong;//洋红
	+ (UIColor *) pinhong;//品红
	+ (UIColor *) fenhong;//粉红
	+ (UIColor *) taohong;//桃红
	+ (UIColor *) haitanghong;//海棠红
	+ (UIColor *) yingtao;//樱桃
	+ (UIColor *) tuoyan;//酡颜
	+ (UIColor *) yinhong;//银红
	+ (UIColor *) dahong;//大红
	+ (UIColor *) shiliuhong;//石榴红
	+ (UIColor *) jiangzi;//绛紫
	+ (UIColor *) feihong;//绯红
	+ (UIColor *) yanzhi;//胭脂
	+ (UIColor *) zhuhong;//朱红
	+ (UIColor *) dan;//丹
	+ (UIColor *) tong;//彤
	+ (UIColor *) tuohong;//酡红
	+ (UIColor *) yan;//炎
	+ (UIColor *) qian;//茜
	+ (UIColor *) wan;//绾
	+ (UIColor *) tan;//檀
	+ (UIColor *) yanhong;//嫣红
	+ (UIColor *) yanghong;//洋红
	+ (UIColor *) zaohong;//枣红
	+ (UIColor *) yanhong;//殷红
	+ (UIColor *) hechi;//赫赤
	+ (UIColor *) yinzhu;//银朱
	+ (UIColor *) chi;//赤
	+ (UIColor *) yanzhi;//胭脂
	+ (UIColor *) li;//栗
	+ (UIColor *) xuan;//玄
	+ (UIColor *) songhua;//松花
	+ (UIColor *) liuhuang;//柳黄
	+ (UIColor *) nenlv;//嫩绿
	+ (UIColor *) liulv;//柳绿
	+ (UIColor *) conghuang;//葱黄
	+ (UIColor *) conglv;//葱绿
	+ (UIColor *) doulv;//豆绿
	+ (UIColor *) douqing;//豆青
	+ (UIColor *) youlv;//油绿
	+ (UIColor *) congqian;//葱倩
	+ (UIColor *) congqing;//葱青
	+ (UIColor *) qingcong;//青葱
	+ (UIColor *) shilv;//石绿
	+ (UIColor *) songbailv;//松柏绿
	+ (UIColor *) songhualv;//松花绿
	+ (UIColor *) lvshen;//绿沈
	+ (UIColor *) lv;//绿
	+ (UIColor *) caolv;//草绿
	+ (UIColor *) qingcui;//青翠
	+ (UIColor *) qing;//青
	+ (UIColor *) feicui;//翡翠
	+ (UIColor *) bilv;//碧绿
	+ (UIColor *) yu;//玉
	+ (UIColor *) piao;//缥
	+ (UIColor *) ailv;//艾绿
	+ (UIColor *) shiqing;//石青
	+ (UIColor *) bi;//碧
	+ (UIColor *) qingbi;//青碧
	+ (UIColor *) tonglv;//铜绿
	+ (UIColor *) zhuqing;//竹青
	+ (UIColor *) mohui;//墨灰
	+ (UIColor *) mo;//墨
	+ (UIColor *) yaqing;//鸦青
	+ (UIColor *) an;//黯
	+ (UIColor *) yingcao;//樱草
	+ (UIColor *) ehuang;//鹅黄
	+ (UIColor *) yahuang;//鸭黄
	+ (UIColor *) xinghuang;//杏黄
	+ (UIColor *) chenghuang;//橙黄
	+ (UIColor *) cheng;//橙
	+ (UIColor *) xinghong;//杏红
	+ (UIColor *) juhuang;//橘黄
	+ (UIColor *) juhong;//橘红
	+ (UIColor *) tenghuang;//藤黄
	+ (UIColor *) jianghuang;//姜黄
	+ (UIColor *) cihuang;//雌黄
	+ (UIColor *) chijin;//赤金
	+ (UIColor *) xiang;//缃
	+ (UIColor *) xionghuang;//雄黄
	+ (UIColor *) qiuxiang;//秋香
	+ (UIColor *) jin;//金
	+ (UIColor *) ya;//牙
	+ (UIColor *) kuhuang;//枯黄
	+ (UIColor *) huanglu;//黄栌
	+ (UIColor *) wujin;//乌金
	+ (UIColor *) hunhuang;//昏黄
	+ (UIColor *) zonghuang;//棕黄
	+ (UIColor *) hupo;//琥珀
	+ (UIColor *) zong;//棕
	+ (UIColor *) cha;//茶
	+ (UIColor *) zonghong;//棕红
	+ (UIColor *) zhe;//赭
	+ (UIColor *) tuo;//驼
	+ (UIColor *) qiu;//秋
	+ (UIColor *) zonglv;//棕绿
	+ (UIColor *) he;//褐
	+ (UIColor *) zonghei;//棕黑
	+ (UIColor *) zhe;//赭
	+ (UIColor *) zheshi;//赭石
	+ (UIColor *) jingbai;//精白
	+ (UIColor *) yinbai;//银白
	+ (UIColor *) qianbai;//铅白
	+ (UIColor *) shuang;//霜
	+ (UIColor *) xuebai;//雪白
	+ (UIColor *) yingbai;//莹白
	+ (UIColor *) yuebai;//月白
	+ (UIColor *) xiangyabai;//象牙白
	+ (UIColor *) gao;//缟
	+ (UIColor *) yudubai;//鱼肚白
	+ (UIColor *) baifen;//白粉
	+ (UIColor *) tubai;//荼白
	+ (UIColor *) yaluanqing;//鸭卵青
	+ (UIColor *) su;//素
	+ (UIColor *) qingbai;//青白
	+ (UIColor *) xiekeqing;//蟹壳青
	+ (UIColor *) huabai;//花白
	+ (UIColor *) laoyin;//老银
	+ (UIColor *) hui;//灰
	+ (UIColor *) cang;//苍
	+ (UIColor *) shui;//水
	+ (UIColor *) you;//黝
	+ (UIColor *) wu;//乌
	+ (UIColor *) xuanqing;//玄青
	+ (UIColor *) wuhei;//乌黑
	+ (UIColor *) li;//黎
	+ (UIColor *) li;//黧
	+ (UIColor *) youhei;//黝黑
	+ (UIColor *) zi;//缁
	+ (UIColor *) meihei;//煤黑
	+ (UIColor *) qihei;//漆黑
	+ (UIColor *) hei;//黑

@end